# Reference agentes.py
#: import main clientes.clientes
#: import ListAdapter kivy.adapters.listadapter.ListAdapter
#: import ListItemButton kivy.uix.listview.ListItemButton
 
Agentes:
<LabelAgentes@Label>
    color:(0,0,0,1)
    halign: 'left'
 
<Agentes>:
    orientation: "vertical"
    num_agent_text_input: num_agent
    first_name_text_input: first_name
    age_agent_text_input: age_agent
    email_agent_text_input: email_agent
    last_name_text_input: last_name
    phoneagent_text_input:phoneagent
    password_agent_input:password_agent
    padding: 10
    spacing: 10

 
    Label:
        text:'Nuevo Agente'
        pos:0,250
        font_size:25
        color:(0,0,0,1)

      
    GridLayout:
        cols:2
        rows:9
        size_hint_y: None
        height: "100dp"
        pos: -5, 350 
        LabelAgentes:
            text: "Numero de Agente"
            width:20
            height:50 
        TextInput:
            id: num_agent
            text:'2332323'
            size_hint: (None, None)
            height: 30
            width: 200
            disabled:True
        LabelAgentes:
            text: "Nombre"
            width:20
            height:50
        TextInput:
            id: first_name
            size_hint: (None, None)
            height: 30
            width: 200
        LabelAgentes:
            text: "Apellido"
            width: 20
            height: 50
        TextInput:
            id: last_name
            size_hint: (None, None)
            height: 30
            width: 200
        LabelAgentes:
            text:"Edad"
        TextInput:
            id:age_agent
            size_hint: (None, None)
            height: 30
            width: 200
        LabelAgentes:
            text:"Correo Electronico"
        TextInput:
            id:email_agent
            size_hint: (None, None)
            height: 30
            width: 200
        LabelAgentes:
            text:"Telefono"
        TextInput:
            id: phoneagent
            size_hint: (None, None)
            height: 30
            width: 200
        LabelAgentes:
            text:"Password"
        TextInput:
            id:password_agent
            size_hint: (None, None)
            height: 30
            width: 200
            password:True
        LabelAgentes:
            text:"Confirmar Password"
        TextInput:
            id:pass_repeat_client
            size_hint: (None, None)
            height: 30
            width: 200
            password:True
        LabelAgentes:
            text:"Fotografia"
        Button:
            id:picture_file
            size_hint: (None, None)
            height: 30
            width: 200
            text:"Seleccionar Fotografia"
            on_release:root.show_load()
            
    BoxLayout:
        size_hint_y: None
        height: "40dp"
        Button:
            text: "Guardar"
            size_hint_x: 15
            on_press: root.submit_agente()
        Button:
            text: "Borrar"
            size_hint_x: 15
        Button:
            text: "Regresar"
            size_hint_x: 15
            on_press: root.go_back()